export const DISCLAIMER =
  'Concept demonstration using synthetic customer, account, billing, usage, network, service, financial, sentiment, offer, and interaction data. Risk scores, recommendations, offers, financial values, and outcomes are illustrative and do not represent actual Rogers customers, production models, approved offers, or business forecasts.'

export type Urgency = 'H0' | 'H1' | 'H2' | 'H3'
export type RiskLevel = 'Critical' | 'High' | 'Medium' | 'Low'
export type QueueStatus =
  | 'New'
  | 'Under review'
  | 'Assigned'
  | 'Contacted'
  | 'Offer presented'
  | 'Saved'
  | 'Declined'
  | 'Churned'
  | 'Monitoring'
  | 'Control group'

export interface Customer {
  id: string
  name: string
  brand: 'Rogers' | 'Fido' | 'chatr'
  product: string
  region: string
  mrc: number
  tenure: number
  clv: number
  risk: number
  percentile: string
  urgency: Urgency
  reason: string
  secondaryReasons: string[]
  revenueAtRisk: number
  channel: string
  nextAction: string
  offerEligible: boolean
  status: QueueStatus
  confidence: number
  expectedSaveValue: number
}

export interface Offer {
  id: string
  name: string
  description: string
  reasons: string[]
  products: string
  brands: string
  minTenure: number
  valueThreshold: string
  marginFloor: string
  maxDiscount: string
  approval: string
  cooldown: string
  channel: string
  acceptance: number
  saveRate: number
  costPerSave: number
  status: 'Draft' | 'Under review' | 'Approved' | 'Active' | 'Paused' | 'Expired' | 'Archived'
  version: string
  compliance: string
  fit: number
  retainedValue: number
  cost: number
}

export const customers: Customer[] = [
  {
    id: 'CTN-8A3F',
    name: 'Sarah Thompson',
    brand: 'Rogers',
    product: 'Wireless only',
    region: 'Ontario',
    mrc: 85,
    tenure: 28,
    clv: 3920,
    risk: 38,
    percentile: 'Top 3%',
    urgency: 'H1',
    reason: 'Contract expiry',
    secondaryReasons: ['Device overdue', 'Service friction'],
    revenueAtRisk: 1020,
    channel: 'Current inbound call',
    nextAction: 'Renewal + device upgrade',
    offerEligible: true,
    status: 'Under review',
    confidence: 91,
    expectedSaveValue: 1760,
  },
  {
    id: 'CTN-5D2K',
    name: 'Liam Chen',
    brand: 'Rogers',
    product: 'Wireless + Internet',
    region: 'British Columbia',
    mrc: 174,
    tenure: 54,
    clv: 8210,
    risk: 82,
    percentile: 'Top 0.5%',
    urgency: 'H0',
    reason: 'Cancel intent',
    secondaryReasons: ['Financial pressure', 'Offer declined'],
    revenueAtRisk: 2088,
    channel: 'Immediate save desk',
    nextAction: 'Plan right-sizing',
    offerEligible: true,
    status: 'Assigned',
    confidence: 96,
    expectedSaveValue: 3620,
  },
  {
    id: 'CTN-2P9M',
    name: 'Maya Singh',
    brand: 'Fido',
    product: 'Wireless only',
    region: 'Alberta',
    mrc: 59,
    tenure: 19,
    clv: 2180,
    risk: 73,
    percentile: 'Top 1%',
    urgency: 'H0',
    reason: 'Competitive port risk',
    secondaryReasons: ['Device overdue'],
    revenueAtRisk: 708,
    channel: 'Outbound call',
    nextAction: 'Device refresh',
    offerEligible: true,
    status: 'New',
    confidence: 88,
    expectedSaveValue: 1120,
  },
  {
    id: 'CTN-7R4Q',
    name: 'Noah Williams',
    brand: 'Rogers',
    product: 'Internet + TV',
    region: 'Ontario',
    mrc: 146,
    tenure: 73,
    clv: 9540,
    risk: 69,
    percentile: 'Top 2%',
    urgency: 'H1',
    reason: 'Service friction',
    secondaryReasons: ['Network quality', 'Financial pressure'],
    revenueAtRisk: 1752,
    channel: 'Supervisor callback',
    nextAction: 'Service recovery',
    offerEligible: true,
    status: 'Contacted',
    confidence: 93,
    expectedSaveValue: 2880,
  },
  {
    id: 'CTN-1V6B',
    name: 'Olivia Martin',
    brand: 'Rogers',
    product: 'Wireless family',
    region: 'Quebec',
    mrc: 212,
    tenure: 42,
    clv: 10120,
    risk: 64,
    percentile: 'Top 4%',
    urgency: 'H1',
    reason: 'Financial pressure',
    secondaryReasons: ['Not converged'],
    revenueAtRisk: 2544,
    channel: 'Inbound care',
    nextAction: 'Family plan optimization',
    offerEligible: true,
    status: 'Offer presented',
    confidence: 86,
    expectedSaveValue: 4100,
  },
  {
    id: 'CTN-3X8J',
    name: 'Ethan Brown',
    brand: 'chatr',
    product: 'Prepaid wireless',
    region: 'Manitoba',
    mrc: 40,
    tenure: 14,
    clv: 920,
    risk: 61,
    percentile: 'Top 6%',
    urgency: 'H1',
    reason: 'Digital disengagement',
    secondaryReasons: ['Brand transition risk'],
    revenueAtRisk: 480,
    channel: 'SMS',
    nextAction: 'Loyalty recognition',
    offerEligible: false,
    status: 'Control group',
    confidence: 72,
    expectedSaveValue: 460,
  },
  {
    id: 'CTN-9N5C',
    name: 'Emma Wilson',
    brand: 'Rogers',
    product: 'Internet only',
    region: 'Nova Scotia',
    mrc: 98,
    tenure: 31,
    clv: 3560,
    risk: 58,
    percentile: 'Top 8%',
    urgency: 'H2',
    reason: 'Network quality',
    secondaryReasons: ['Service friction'],
    revenueAtRisk: 1176,
    channel: 'Technical callback',
    nextAction: 'Technical resolution',
    offerEligible: true,
    status: 'Monitoring',
    confidence: 89,
    expectedSaveValue: 1640,
  },
  {
    id: 'CTN-4H7S',
    name: 'Lucas Tremblay',
    brand: 'Fido',
    product: 'Wireless only',
    region: 'Quebec',
    mrc: 65,
    tenure: 25,
    clv: 2640,
    risk: 56,
    percentile: 'Top 9%',
    urgency: 'H2',
    reason: 'Device overdue',
    secondaryReasons: ['Contract expiry'],
    revenueAtRisk: 780,
    channel: 'In-app',
    nextAction: 'Device upgrade',
    offerEligible: true,
    status: 'New',
    confidence: 84,
    expectedSaveValue: 1220,
  },
  {
    id: 'CTN-6F1A',
    name: 'Ava Patel',
    brand: 'Rogers',
    product: 'Wireless + Internet',
    region: 'Ontario',
    mrc: 168,
    tenure: 61,
    clv: 7890,
    risk: 54,
    percentile: 'Top 10%',
    urgency: 'H2',
    reason: 'Payment difficulty',
    secondaryReasons: ['Financial pressure'],
    revenueAtRisk: 2016,
    channel: 'Inbound care',
    nextAction: 'Payment arrangement',
    offerEligible: true,
    status: 'Under review',
    confidence: 81,
    expectedSaveValue: 2780,
  },
  {
    id: 'CTN-8L3D',
    name: 'Benjamin Davis',
    brand: 'Rogers',
    product: 'Wireless only',
    region: 'Alberta',
    mrc: 92,
    tenure: 38,
    clv: 4340,
    risk: 51,
    percentile: 'Top 12%',
    urgency: 'H2',
    reason: 'Contract expiry',
    secondaryReasons: ['Not converged'],
    revenueAtRisk: 1104,
    channel: 'Email',
    nextAction: 'Proactive renewal',
    offerEligible: true,
    status: 'Contacted',
    confidence: 87,
    expectedSaveValue: 1820,
  },
  {
    id: 'CTN-2W7E',
    name: 'Sophia Anderson',
    brand: 'Fido',
    product: 'Wireless only',
    region: 'British Columbia',
    mrc: 52,
    tenure: 17,
    clv: 1960,
    risk: 48,
    percentile: 'Top 15%',
    urgency: 'H2',
    reason: 'Retention offer declined',
    secondaryReasons: ['Competitive port risk'],
    revenueAtRisk: 624,
    channel: 'Outbound call',
    nextAction: 'Alternative value offer',
    offerEligible: true,
    status: 'Declined',
    confidence: 76,
    expectedSaveValue: 840,
  },
  {
    id: 'CTN-5K9T',
    name: 'William Moore',
    brand: 'Rogers',
    product: 'Internet + TV + Home Phone',
    region: 'Ontario',
    mrc: 224,
    tenure: 96,
    clv: 14200,
    risk: 45,
    percentile: 'Top 18%',
    urgency: 'H2',
    reason: 'Financial pressure',
    secondaryReasons: ['Digital disengagement'],
    revenueAtRisk: 2688,
    channel: 'Outbound call',
    nextAction: 'Plan right-sizing',
    offerEligible: true,
    status: 'Saved',
    confidence: 79,
    expectedSaveValue: 4860,
  },
  {
    id: 'CTN-7C2Y',
    name: 'Isabella Roy',
    brand: 'Rogers',
    product: 'Wireless + Internet',
    region: 'Quebec',
    mrc: 158,
    tenure: 47,
    clv: 6760,
    risk: 43,
    percentile: 'Top 20%',
    urgency: 'H3',
    reason: 'Not converged',
    secondaryReasons: ['Contract expiry'],
    revenueAtRisk: 1896,
    channel: 'MyRogers journey',
    nextAction: 'Convergence offer',
    offerEligible: true,
    status: 'Monitoring',
    confidence: 83,
    expectedSaveValue: 2410,
  },
  {
    id: 'CTN-1M4G',
    name: 'James Taylor',
    brand: 'chatr',
    product: 'Prepaid wireless',
    region: 'Saskatchewan',
    mrc: 35,
    tenure: 22,
    clv: 1050,
    risk: 41,
    percentile: 'Top 22%',
    urgency: 'H3',
    reason: 'Brand transition risk',
    secondaryReasons: ['Digital disengagement'],
    revenueAtRisk: 420,
    channel: 'SMS',
    nextAction: 'Brand transition journey',
    offerEligible: true,
    status: 'New',
    confidence: 70,
    expectedSaveValue: 510,
  },
  {
    id: 'CTN-9B6P',
    name: 'Mia Johnson',
    brand: 'Rogers',
    product: 'Wireless family',
    region: 'Ontario',
    mrc: 245,
    tenure: 67,
    clv: 12680,
    risk: 39,
    percentile: 'Top 25%',
    urgency: 'H3',
    reason: 'Device overdue',
    secondaryReasons: ['Contract expiry'],
    revenueAtRisk: 2940,
    channel: 'In-app',
    nextAction: 'Family device refresh',
    offerEligible: true,
    status: 'Assigned',
    confidence: 85,
    expectedSaveValue: 5240,
  },
  {
    id: 'CTN-3Q8R',
    name: 'Alexander Clark',
    brand: 'Rogers',
    product: 'Internet only',
    region: 'New Brunswick',
    mrc: 89,
    tenure: 29,
    clv: 3180,
    risk: 36,
    percentile: 'Top 28%',
    urgency: 'H3',
    reason: 'Service friction',
    secondaryReasons: ['Network quality'],
    revenueAtRisk: 1068,
    channel: 'Email',
    nextAction: 'Service assurance',
    offerEligible: true,
    status: 'Monitoring',
    confidence: 82,
    expectedSaveValue: 1380,
  },
  {
    id: 'CTN-6J5V',
    name: 'Charlotte White',
    brand: 'Fido',
    product: 'Wireless only',
    region: 'Alberta',
    mrc: 58,
    tenure: 34,
    clv: 2880,
    risk: 34,
    percentile: 'Top 31%',
    urgency: 'H3',
    reason: 'Contract expiry',
    secondaryReasons: ['Financial pressure'],
    revenueAtRisk: 696,
    channel: 'In-app',
    nextAction: 'Renewal reminder',
    offerEligible: false,
    status: 'Control group',
    confidence: 78,
    expectedSaveValue: 970,
  },
  {
    id: 'CTN-4Z1N',
    name: 'Henry Scott',
    brand: 'Rogers',
    product: 'Wireless + Internet + TV',
    region: 'British Columbia',
    mrc: 286,
    tenure: 112,
    clv: 18400,
    risk: 31,
    percentile: 'Top 35%',
    urgency: 'H3',
    reason: 'Digital disengagement',
    secondaryReasons: ['Financial pressure'],
    revenueAtRisk: 3432,
    channel: 'Relationship manager',
    nextAction: 'Loyalty recognition',
    offerEligible: true,
    status: 'Saved',
    confidence: 74,
    expectedSaveValue: 6100,
  },
]

export const offers: Offer[] = [
  {
    id: 'OFF-2401',
    name: 'Device upgrade + renewal',
    description: 'Eligible premium device upgrade with a 24-month plan renewal.',
    reasons: ['Contract expiry', 'Device overdue'],
    products: 'Postpaid wireless',
    brands: 'Rogers, Fido',
    minTenure: 12,
    valueThreshold: 'Medium+',
    marginFloor: '32%',
    maxDiscount: '$15/month',
    approval: 'Agent authority',
    cooldown: '90 days',
    channel: 'Care, retention, digital',
    acceptance: 76,
    saveRate: 71,
    costPerSave: 184,
    status: 'Active',
    version: '4.2',
    compliance: 'Approved',
    fit: 96,
    retainedValue: 1760,
    cost: 168,
  },
  {
    id: 'OFF-2414',
    name: 'Service-recovery credit',
    description: 'One-time acknowledgement credit following confirmed service friction.',
    reasons: ['Service friction', 'Network quality'],
    products: 'All',
    brands: 'All',
    minTenure: 3,
    valueThreshold: 'All',
    marginFloor: 'Policy exception',
    maxDiscount: '$50 once',
    approval: 'Agent up to $35',
    cooldown: '180 days',
    channel: 'Care, retention',
    acceptance: 69,
    saveRate: 57,
    costPerSave: 112,
    status: 'Active',
    version: '3.8',
    compliance: 'Approved',
    fit: 91,
    retainedValue: 1380,
    cost: 35,
  },
  {
    id: 'OFF-2388',
    name: 'Plan right-sizing',
    description: 'Align plan and included usage to observed needs and affordability.',
    reasons: ['Financial pressure', 'Payment difficulty'],
    products: 'Wireless',
    brands: 'Rogers, Fido',
    minTenure: 6,
    valueThreshold: 'All',
    marginFloor: '28%',
    maxDiscount: '$20/month',
    approval: 'Supervisor below floor',
    cooldown: '60 days',
    channel: 'Care, retention',
    acceptance: 63,
    saveRate: 54,
    costPerSave: 206,
    status: 'Active',
    version: '2.6',
    compliance: 'Approved',
    fit: 72,
    retainedValue: 1260,
    cost: 144,
  },
  {
    id: 'OFF-2420',
    name: 'Renewal discount',
    description: 'Time-bound renewal value for eligible contract-expiry customers.',
    reasons: ['Contract expiry'],
    products: 'Postpaid wireless',
    brands: 'Rogers',
    minTenure: 18,
    valueThreshold: 'Medium+',
    marginFloor: '35%',
    maxDiscount: '$10/month',
    approval: 'Agent authority',
    cooldown: '120 days',
    channel: 'Retention, outbound',
    acceptance: 66,
    saveRate: 59,
    costPerSave: 194,
    status: 'Active',
    version: '1.9',
    compliance: 'Approved',
    fit: 84,
    retainedValue: 1490,
    cost: 120,
  },
  {
    id: 'OFF-2355',
    name: 'Data bonus',
    description: 'Additional high-speed data for usage-led value concerns.',
    reasons: ['Financial pressure', 'Competitive port risk'],
    products: 'Wireless',
    brands: 'Rogers, Fido',
    minTenure: 9,
    valueThreshold: 'All',
    marginFloor: '38%',
    maxDiscount: '5 GB',
    approval: 'Agent authority',
    cooldown: '90 days',
    channel: 'Digital, care',
    acceptance: 61,
    saveRate: 48,
    costPerSave: 131,
    status: 'Active',
    version: '2.2',
    compliance: 'Approved',
    fit: 45,
    retainedValue: 920,
    cost: 44,
  },
  {
    id: 'OFF-2371',
    name: 'Roaming benefit',
    description: 'Limited roaming benefit for customers with qualifying travel patterns.',
    reasons: ['Competitive port risk'],
    products: 'Wireless',
    brands: 'Rogers',
    minTenure: 12,
    valueThreshold: 'High',
    marginFloor: '40%',
    maxDiscount: '7 travel days',
    approval: 'Agent authority',
    cooldown: '180 days',
    channel: 'Retention',
    acceptance: 54,
    saveRate: 44,
    costPerSave: 226,
    status: 'Approved',
    version: '1.4',
    compliance: 'Approved',
    fit: 29,
    retainedValue: 880,
    cost: 96,
  },
  {
    id: 'OFF-2433',
    name: 'Family-line incentive',
    description: 'Add or preserve an eligible family line with a governed incentive.',
    reasons: ['Financial pressure', 'Not converged'],
    products: 'Wireless family',
    brands: 'Rogers',
    minTenure: 12,
    valueThreshold: 'High',
    marginFloor: '33%',
    maxDiscount: '$15/month',
    approval: 'Supervisor',
    cooldown: '120 days',
    channel: 'Retention',
    acceptance: 58,
    saveRate: 62,
    costPerSave: 248,
    status: 'Active',
    version: '3.1',
    compliance: 'Approved',
    fit: 38,
    retainedValue: 2130,
    cost: 180,
  },
  {
    id: 'OFF-2320',
    name: 'Ignite bundle',
    description: 'Eligible Ignite bundle migration with value and service review.',
    reasons: ['Not converged', 'Financial pressure'],
    products: 'Home services',
    brands: 'Rogers',
    minTenure: 6,
    valueThreshold: 'Medium+',
    marginFloor: '31%',
    maxDiscount: '$25/month',
    approval: 'Supervisor',
    cooldown: '180 days',
    channel: 'Care, retail',
    acceptance: 49,
    saveRate: 55,
    costPerSave: 318,
    status: 'Active',
    version: '5.0',
    compliance: 'Approved',
    fit: 12,
    retainedValue: 2540,
    cost: 300,
  },
  {
    id: 'OFF-2342',
    name: 'Home Internet bundle',
    description: 'Converged wireless and home Internet value package.',
    reasons: ['Not converged'],
    products: 'Wireless only',
    brands: 'Rogers',
    minTenure: 9,
    valueThreshold: 'Medium+',
    marginFloor: '34%',
    maxDiscount: '$20/month',
    approval: 'Supervisor',
    cooldown: '180 days',
    channel: 'Outbound, retail',
    acceptance: 46,
    saveRate: 51,
    costPerSave: 344,
    status: 'Active',
    version: '2.4',
    compliance: 'Approved',
    fit: 31,
    retainedValue: 2860,
    cost: 240,
  },
  {
    id: 'OFF-2399',
    name: 'Loyalty reward',
    description: 'Recognition benefit for eligible long-tenure customers.',
    reasons: ['Digital disengagement', 'Retention offer declined'],
    products: 'All',
    brands: 'Rogers, Fido',
    minTenure: 36,
    valueThreshold: 'Medium+',
    marginFloor: '36%',
    maxDiscount: '$75 value',
    approval: 'Agent authority',
    cooldown: '365 days',
    channel: 'All assisted',
    acceptance: 71,
    saveRate: 53,
    costPerSave: 158,
    status: 'Active',
    version: '1.7',
    compliance: 'Approved',
    fit: 48,
    retainedValue: 1180,
    cost: 75,
  },
  {
    id: 'OFF-2451',
    name: 'Premium support',
    description: 'Priority support pathway for eligible high-value relationships.',
    reasons: ['Service friction'],
    products: 'All',
    brands: 'Rogers',
    minTenure: 24,
    valueThreshold: 'High',
    marginFloor: '40%',
    maxDiscount: 'Service benefit',
    approval: 'Supervisor',
    cooldown: '365 days',
    channel: 'Retention',
    acceptance: 57,
    saveRate: 61,
    costPerSave: 172,
    status: 'Under review',
    version: '0.9',
    compliance: 'Review required',
    fit: 67,
    retainedValue: 1620,
    cost: 82,
  },
  {
    id: 'OFF-2460',
    name: 'Technical resolution callback',
    description: 'Priority technical follow-up before any commercial intervention.',
    reasons: ['Network quality', 'Service friction'],
    products: 'All',
    brands: 'All',
    minTenure: 0,
    valueThreshold: 'All',
    marginFloor: 'Not applicable',
    maxDiscount: 'None',
    approval: 'No offer approval',
    cooldown: '30 days',
    channel: 'Technical care',
    acceptance: 81,
    saveRate: 49,
    costPerSave: 96,
    status: 'Active',
    version: '2.0',
    compliance: 'Approved',
    fit: 79,
    retainedValue: 1100,
    cost: 28,
  },
]

export const churnTrend = [
  { month: 'Apr', churn: 1.74, save: 62, control: 54 },
  { month: 'May', churn: 1.69, save: 63, control: 54 },
  { month: 'Jun', churn: 1.72, save: 65, control: 55 },
  { month: 'Jul', churn: 1.64, save: 66, control: 56 },
  { month: 'Aug', churn: 1.61, save: 67, control: 57 },
  { month: 'Sep', churn: 1.58, save: 68, control: 59.6 },
]

export const riskDistribution = [
  { name: 'Critical', value: 2140, colour: '#f43f5e' },
  { name: 'High', value: 6320, colour: '#ef4444' },
  { name: 'Medium', value: 18460, colour: '#f59e0b' },
  { name: 'Low', value: 97880, colour: '#10b981' },
]

export const channelPerformance = [
  { channel: 'Save desk', save: 74, acceptance: 81 },
  { channel: 'Inbound care', save: 68, acceptance: 76 },
  { channel: 'Outbound', save: 59, acceptance: 64 },
  { channel: 'Digital', save: 51, acceptance: 58 },
  { channel: 'Retail', save: 63, acceptance: 69 },
]

export const campaigns = [
  { name: 'Proactive renewal', eligible: 18200, contacted: 11240, accepted: 4210, saved: 3860, control: 2400, natural: 58, intervention: 71, lift: 13, cost: 0.72, retained: 5.1, roi: 5.4 },
  { name: 'Device refresh', eligible: 14900, contacted: 8940, accepted: 3540, saved: 3110, control: 2100, natural: 56, intervention: 68, lift: 12, cost: 0.81, retained: 4.4, roi: 4.4 },
  { name: 'Service recovery', eligible: 9200, contacted: 7180, accepted: 2840, saved: 2470, control: 1400, natural: 49, intervention: 65, lift: 16, cost: 0.39, retained: 2.6, roi: 5.7 },
  { name: 'Plan right-sizing', eligible: 11600, contacted: 7240, accepted: 2320, saved: 1960, control: 1750, natural: 52, intervention: 62, lift: 10, cost: 0.61, retained: 2.8, roi: 3.6 },
  { name: 'Bundle + convergence', eligible: 7600, contacted: 4180, accepted: 1260, saved: 1080, control: 1150, natural: 61, intervention: 69, lift: 8, cost: 0.52, retained: 2.2, roi: 3.2 },
  { name: 'Immediate save desk', eligible: 4300, contacted: 4200, accepted: 2760, saved: 2380, control: 600, natural: 21, intervention: 57, lift: 36, cost: 0.88, retained: 4.9, roi: 4.6 },
  { name: 'Loyalty recognition', eligible: 6800, contacted: 3720, accepted: 1190, saved: 910, control: 1020, natural: 67, intervention: 72, lift: 5, cost: 0.44, retained: 1.4, roi: 2.2 },
]

export const agentDefinitions = [
  { name: 'Retention Supervisor Agent', short: 'Supervisor', task: 'Orchestrate workflow and apply authority rules', input: 'Interaction event + shared state', output: 'Final governed recommendation', confidence: 94, authority: 'Route and recommend' },
  { name: 'Churn Prediction Agent', short: 'Prediction', task: 'Refresh multi-horizon risk and urgency', input: 'Customer signals + event', output: '38% risk · H1 · top 3%', confidence: 91, authority: 'Observe and score' },
  { name: 'Customer 360 and Explanation Agent', short: 'Explanation', task: 'Assemble context and explain drivers', input: 'Signals + model output', output: 'Expiry, device, service friction', confidence: 93, authority: 'Observe and explain' },
  { name: 'Next-Best-Retention-Action Agent', short: 'Action', task: 'Rank eligible governed actions', input: 'Reasons + value + offer rules', output: 'Upgrade + renewal + recovery', confidence: 89, authority: 'Recommend only' },
  { name: 'Conversation and Outcome Agent', short: 'Conversation', task: 'Coach conversation and record outcome', input: 'Recommendation + transcript', output: 'Talk track + outcome schema', confidence: 92, authority: 'Assist and record' },
]

export const explanationModes = {
  Executive:
    'Sarah is in the top 3% of simulated churn risk. The preventable value is concentrated around an expiring contract, an overdue device, and a service experience that has not yet been acknowledged.',
  Frontline:
    'Start with the service concern, then ask about device needs. A generic discount is unlikely to resolve the combination of frustration and an old phone.',
  'Data science':
    'Illustrative additive contributions move the synthetic baseline from 6% to 38%. Contract expiry contributes +14 points, device age +8, service friction +5, non-convergence +3, financial sensitivity +3 net, and digital engagement -1.',
  Audit:
    'Score CHURN-90D-v4.7 was refreshed at 10:42 ET using approved synthetic features. Explanation completeness is 96%; no protected attributes are used.',
}

export const contributions = [
  { name: 'Base probability', value: 6, type: 'base' },
  { name: 'Contract expiry', value: 14, type: 'risk' },
  { name: 'Device overdue', value: 8, type: 'risk' },
  { name: 'Service friction', value: 5, type: 'risk' },
  { name: 'Not converged', value: 3, type: 'risk' },
  { name: 'Financial sensitivity', value: 3, type: 'risk' },
  { name: 'Digital engagement', value: -1, type: 'protective' },
]

export const timeline = [
  { date: 'Aug 18', title: 'Service disruption', detail: 'Synthetic network incident exposure registered', type: 'Observed signal' },
  { date: 'Aug 19', title: 'Care contact', detail: 'Customer requested service status and billing review', type: 'Observed signal' },
  { date: 'Aug 21', title: 'Negative sentiment', detail: 'Frustration detected in interaction summary', type: 'Agent inference' },
  { date: 'Sep 12', title: 'Bill viewed', detail: 'Three digital bill-detail views in 48 hours', type: 'Observed signal' },
  { date: 'Sep 23', title: 'Upgrade page visited', detail: 'Premium device comparison viewed twice', type: 'Observed signal' },
  { date: 'Sep 28', title: 'Expiry threshold', detail: 'Contract entered 14-day renewal window', type: 'Business rule' },
  { date: 'Today · 10:41', title: 'Inbound retention call', detail: 'Customer expressed switching consideration', type: 'Human interaction' },
  { date: 'Today · 10:42', title: 'Event-triggered re-score', detail: 'Risk updated from 31% to 38%', type: 'Model prediction' },
]

export const conversationSteps = [
  {
    speaker: 'Customer',
    text: 'My bill keeps going up, my phone is old, and after the service problems last month I’m wondering if I should switch.',
    coaching: 'Acknowledge the recent service issue before discussing price.',
  },
  {
    speaker: 'Agent',
    text: 'I’m sorry the recent service issues added to the frustration. Let me review your account and see whether I can address both the service concern and your device situation.',
    coaching: 'Confirm whether the customer wants to keep the current device or upgrade.',
  },
  {
    speaker: 'Customer',
    text: 'I would upgrade if the monthly cost stays reasonable. I do not want another surprise on my bill.',
    coaching: 'Explain the total monthly value clearly. Do not describe the churn score.',
  },
  {
    speaker: 'Agent',
    text: 'I can review an eligible device upgrade and renewal option that keeps the plan within an approved affordability threshold. I can also acknowledge the recent service disruption with a one-time credit.',
    coaching: 'Confirm consent before changing the plan or presenting final terms.',
  },
  {
    speaker: 'Customer',
    text: 'That sounds worth reviewing. Please show me the full monthly amount and any one-time fees.',
    coaching: 'Present the governed offer, disclose terms, and confirm understanding.',
  },
]

export const auditSteps = [
  ['10:41:02', 'Retention Supervisor Agent', 'Interaction event', 'Inbound retention context created', '99%', 'Purpose + access policy', 'Employee initiated', 'Contact-centre event', 'Passed'],
  ['10:41:05', 'Churn Prediction Agent', 'Feature vector', 'Event-triggered re-score requested', '96%', 'Approved model only', 'None', 'Feature store snapshot', 'Passed'],
  ['10:41:08', 'Churn Prediction Agent', 'Model output', '38% 90-day risk returned', '91%', 'CHURN-90D-v4.7', 'None', 'Model endpoint simulation', 'Passed'],
  ['10:41:09', 'Retention Supervisor Agent', 'Risk ranking', 'Top 3% percentile · H1 urgency', '94%', 'Urgency policy v2.3', 'None', 'Score distribution', 'Passed'],
  ['10:41:12', 'Customer 360 and Explanation Agent', 'Customer signals', 'Expiry, device age, service friction', '93%', 'Explanation policy', 'Reviewable', 'Synthetic source lineage', 'Passed'],
  ['10:41:16', 'Next-Best-Retention-Action Agent', 'Offer catalogue', '12 interventions evaluated', '92%', 'Eligibility policy', 'None', 'Offer catalogue v6.1', 'Passed'],
  ['10:41:17', 'Next-Best-Retention-Action Agent', 'Excluded offers', '9 removed by fit, product, or status', '98%', 'Cooldown + margin', 'None', 'Rules engine simulation', 'Passed'],
  ['10:41:19', 'Next-Best-Retention-Action Agent', 'Eligible offers', 'Primary and fallback ranked', '89%', 'Expected value policy', 'Review required', 'Recommendation model', 'Passed'],
  ['10:41:24', 'Conversation and Outcome Agent', 'Recommendation', 'Employee talk track prepared', '92%', 'Disclosure policy', 'Employee reviews', 'Approved content library', 'Passed'],
  ['Pending', 'Conversation and Outcome Agent', 'Interaction outcome', 'Awaiting human-recorded outcome', '—', 'Outcome completeness', 'Required', 'Employee input', 'Open'],
]

export const walkthrough = [
  { title: 'Knowing who may churn is not the same as preventing churn.', text: 'Traditional churn programmes often produce a risk score or a target list. The frontline still needs to understand why the customer is at risk, whether the moment is urgent, what action is appropriate, and whether the intervention is economically sound.', route: '/', focus: 'Executive opportunity' },
  { title: 'The system scores daily and responds to important customer events.', text: 'The Churn Prediction Agent refreshes risk on a regular cadence and can respond to events such as a cancel-flow visit, service issue, billing change, negative sentiment, or competitive port signal.', route: '/customer', focus: 'Event-triggered re-score' },
  { title: 'Sarah is at risk, but the score alone is not the answer.', text: 'Sarah is in the top simulated risk percentile. The Customer 360 and Explanation Agent shows that her risk is primarily related to contract expiry, an overdue device, and recent service friction.', route: '/customer', focus: 'Risk explanation' },
  { title: 'The same risk score can require a different action depending on timing.', text: 'Sarah is classified as H1 because the intervention window is between eight and thirty days. An immediate cancel signal would be H0, while early disengagement may be handled through a longer-term journey.', route: '/queue', focus: 'Urgency horizons' },
  { title: 'The recommendation addresses the reason, not just the probability.', text: 'The Next-Best-Retention-Action Agent evaluates offer eligibility, likely acceptance, customer lifetime value, margin, channel, offer history, and the actual churn drivers.', route: '/offers', focus: 'Next-best action' },
  { title: 'AI provides one clear recommendation. The employee decides what to present.', text: 'The employee can inspect the evidence, use the generated talk track, present the recommendation, select the fallback, request approval, modify within authority, or reject the recommendation.', route: '/assist', focus: 'Human decision controls' },
  { title: 'The right save starts with acknowledging the customer’s actual concern.', text: 'The Conversation Agent recommends acknowledging the service problem before discussing price. It then helps the employee explain the device and renewal option in clear language.', route: '/assist', focus: 'Live conversation' },
  { title: 'Every accepted, declined, or modified recommendation becomes learning data.', text: 'The outcome is written to the simulated measurement layer. Rogers can determine which interventions work for which churn reasons, customer segments, channels, and urgency horizons.', route: '/assist', focus: 'Outcome capture' },
  { title: 'Save rate alone is not enough. Rogers must measure lift over control.', text: 'The executive dashboard distinguishes natural retention from incremental retention. It tracks save rate, lift, cost per save, revenue retained, offer cost, and campaign ROI.', route: '/performance', focus: 'Incremental performance' },
  { title: 'Move from predicting churn to continuously preventing it.', text: 'The solution connects customer signals, predictive models, explainability, offer decisioning, frontline assistance, governance, and outcome measurement into one closed-loop retention system.', route: '/architecture', focus: 'Closed-loop system' },
]

export const reasonCodes = [
  ['CONTRACT_EXPIRY', 'Contract expiry', 'Contract is approaching renewal or expiry', 'H1', 'Contract, renewal, tenure', 'Proactive renewal', 'Inbound or outbound', 'Over-discounting', 'High', 'Offer policy'],
  ['DEVICE_OVERDUE', 'Device overdue', 'Device age exceeds expected refresh cycle', 'H1-H2', 'Device age, upgrade views', 'Device upgrade', 'Digital or care', 'Affordability', 'High', 'Credit and offer'],
  ['SERVICE_FRICTION', 'Service friction', 'Recent unresolved service experience', 'H0-H1', 'Care, complaint, sentiment', 'Service recovery', 'Care callback', 'Premature selling', 'High', 'Credit authority'],
  ['FINANCIAL_PRESSURE', 'Financial pressure', 'Signals indicate affordability sensitivity', 'H0-H2', 'Bills, plan usage, contacts', 'Plan right-sizing', 'Care', 'Customer vulnerability', 'Medium', 'Margin rule'],
  ['CANCEL_INTENT', 'Cancel intent', 'Explicit cancellation or switching signal', 'H0', 'Call intent, cancel flow', 'Immediate save desk', 'Live assisted', 'High pressure', 'High', 'Human approval'],
  ['RETENTION_OFFER_DECLINED', 'Offer declined', 'Previous retention intervention was declined', 'H0-H1', 'Offer history, outcome', 'Alternative action', 'Assisted', 'Offer fatigue', 'High', 'Cooldown'],
  ['DIGITAL_DISENGAGEMENT', 'Digital disengagement', 'Declining engagement with owned channels', 'H2-H3', 'App and web activity', 'Re-engagement', 'Digital', 'False positives', 'Medium', 'Consent'],
  ['NOT_CONVERGED', 'Not converged', 'Single-product relationship has bundle potential', 'H2-H3', 'Product holdings', 'Convergence review', 'Outbound', 'Unwanted cross-sell', 'Medium', 'Eligibility'],
  ['PAYMENT_DIFFICULTY', 'Payment difficulty', 'Recent payment challenges are present', 'H0-H2', 'Payment events', 'Payment support', 'Care', 'Sensitive treatment', 'High', 'Vulnerability'],
  ['BRAND_TRANSITION_RISK', 'Brand transition risk', 'Customer may be better aligned to another brand path', 'H2-H3', 'Plan and usage fit', 'Brand transition', 'Digital or care', 'Confusion', 'Medium', 'Brand policy'],
  ['NETWORK_QUALITY', 'Network quality', 'Repeated quality or outage exposure', 'H0-H1', 'Network events, contacts', 'Technical resolution', 'Technical care', 'Unsupported claim', 'High', 'Incident validation'],
  ['COMPETITIVE_PORT_RISK', 'Competitive port risk', 'Signals suggest possible competitor port activity', 'H0-H1', 'Port inquiry, intent', 'Immediate save', 'Live assisted', 'Misclassification', 'Medium', 'Evidence review'],
]
